import { test, expect } from '@playwright/test';

test.only('This was generated by codegen', async ({ page }) => {
  await page.goto('https://the-internet.herokuapp.com/login');
  await page.pause(); // added by me-important
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tomsmith');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('SuperSecretPassword!');
  await page.getByRole('button', { name: ' Login' }).click();
  await expect(page.getByRole('heading', { name: 'Secure Area', exact: true })).toBeVisible();
  await expect(page.locator('h4')).toContainText('Welcome to the Secure Area. When you are done click logout below.');
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('test');
  await expect(page.getByRole('textbox', { name: 'Username' })).toHaveValue('test');
  await page.pause(); // added by me-important
});