name: Sourcery
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
          check: true  # Set to either true or false as needed
          in_place: false  # Set to either true or false as needed
          verbose: true  # Set to either true or false as needed